name: Pull Request Title Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  validate-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

    - name: semantic-pull-request
      uses: amannn/action-semantic-pull-request@v5.5.3
      id: lint_pr_title
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: marocchino/sticky-pull-request-comment@v2
      if: always() && (steps.lint_pr_title.outputs.error_message != null)
      with:
        header: pr-title-lint-error
        message: |
          We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.
          Details:

          ```
          ${{ steps.lint_pr_title.outputs.error_message }}
          ```

    - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: pr-title-lint-error
        delete: true